[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.140.1"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.140.1"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.140.1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect apex domain to www (optional)
# [[redirects]]
#   from = "https://calebwastaken.com/*"
#   to = "https://www.calebwastaken.com/:splat"
#   status = 301
#   force = true
